### ISSUE TITLE
<<ListboxSelect>> event

### ISSUE THREAD

**Issue by WK-GiHu** [n00by0815/Image-Viewer#2]
@n00by0815 

1. Here you bind to a single `Listbox`
  https://github.com/n00by0815/Image-Viewer/blob/649c9136ac7ab9159d8faa7e0898258d2c0e198d/image_viewer.py#L32

2. This is your `callback`
  https://github.com/n00by0815/Image-Viewer/blob/649c9136ac7ab9159d8faa7e0898258d2c0e198d/image_viewer.py#L43

Insert after Line 43
```
print('on _select({})'.format(event.type))
```

and see what you get.

**Comment by n00by0815** [comment]
Done, see [commit](https://github.com/n00by0815/Image-Viewer/commit/b78aed8f520a8588f374e7d5296d6aaa44e4c9a0#diff-8b309ac51f296799569ca571ab1f9743)

**Comment by n00by0815** [comment]
I know that I get the output this way. The only question I have is, how I can get that information into ClassTwo and ClassThree? Do I check MultilistBox.currentselection? And if that has changed, I trigger an action. Or can I somehow achieve the same behaviour, as .bind() would normally provide?

**Comment by WK-GiHu** [comment]
@n00by0815 

>And if that has changed, I trigger an action. 

You don't have to observe **"has changed"**, you have to react on event `<<ListboxSelect>>`.

---

>Or can I somehow achieve the same behaviour, as `.bind()` would normally provide?

Yes, you can, it's your decision:

- [ ] 1. Call a `callback` on event `<<ListboxSelect>>`
  - [ ] 1. Overload `MultiListbox.bind(...` to allow `.bind(...` like this :
  `self.available_images_lb.bind('<<ListboxSelect>>', self.print_stuff_two)`
  - [ ] 2. Extend `MultiListbox.__init__(callback=`
- [x] 2. Echo the `Listbox <<ListboxSelect>>` event to `MultiListbox(Frame)` to get this working:
  `self.available_images_lb.bind('<<MultiListboxSelect>>', self.print_stuff_two)`
Make your decision.

**Comment by n00by0815** [comment]
What would be your suggestion? I would like to be able to also use Multilistbox in future applications, so whatever turns out to be the more flexible solution, is what I'd like to use. Thank you for your help so far! I still find tkinter pretty confusing at times...

**Comment by n00by0815** [comment]
Let me change my answer here. I am still open to your suggestion, as you simply are far more knowledgable in this area than me. But couldn't overloading become a problem later on and cause unwanted side effects? For example when I combine a regular `Listbox` and a `MultiListbox` in one application? I also guess it is easier for others to see later on which lines interact with `<<MultiListboxSelect>>` compared to the regular looking `<<ListboxSelect>>`
