### ISSUE TITLE
Implement `<<MultiListboxSelect>>`

### ISSUE THREAD

**Issue by WK-GiHu** [n00by0815/Image-Viewer#4]
Let me change my answer here. I am still open to your suggestion, as you simply are far more knowledgable in this area than me. But couldn't overloading become a problem later on and cause unwanted side effects? For example when I combine a regular `Listbox` and a `MultiListbox` in one application? I also guess it is easier for others to see later on which lines interact with `<<MultiListboxSelect>>` compared to the regular looking `<<ListboxSelect>>`

_Originally posted by @n00by0815 in https://github.com/n00by0815/Image-Viewer/issues/2#issuecomment-574150865_

**Comment by WK-GiHu** [comment]
@n00by0815 

>- [X] 2. Echo the Listbox <<ListboxSelect>> event to MultiListbox(Frame)

Yes this is also my suggestion.

>I also guess it is easier for others to see later on which lines interact with `<<MultiListboxSelect>>`

Yes, you allready use 
`self.available_images_lb.bind('<<ListboxSelect>>', self.print_stuff_two)`
You have to replace only the event name with: `'<<MultiListboxSelect>>'`

---

Insert after Line 48
https://github.com/n00by0815/Image-Viewer/blob/b78aed8f520a8588f374e7d5296d6aaa44e4c9a0/image_viewer.py#L48

```
self.event_generate('<<MultiListboxSelect>>', when='tail')
```
Enable Line 147
https://github.com/n00by0815/Image-Viewer/blob/b78aed8f520a8588f374e7d5296d6aaa44e4c9a0/image_viewer.py#L147

change to

```
self.available_images_lb.bind('<<MultiListboxSelect>>', self.print_stuff_two)
```

**Comment by n00by0815** [comment]
THANK YOU SOOO MUCH! I can't believe how easy that was and I actually feel a bit stupid now... That does exactly what I needed it to do.

**Comment by n00by0815** [comment]
See: [Implementation of MultiListboxSelect](https://github.com/n00by0815/Image-Viewer/commit/5814c5256b2f638727cfcb1dd19e082253299f1e) for the implementation.

**Comment by n00by0815** [comment]
Would you be willing to describe the solution on Stackoverflow and link to this repo, or copy the code, so others who have the same or similar problem can find the solution more easily? Then I can also accept your answer there and upvote it.
